Repository Winterwood0118/ContactApp, pull requests merged in 2024-04, with the labels that each got.

#5 싱글톤 디자인 완성
  app/src/main/java/com/example/contactapp/data/ContactInformation.kt
  app/src/main/java/com/example/contactapp/data/DataSource.kt
  app/src/main/java/com/example/contactapp/data/data.kt
  app/src/main/java/com/example/contactapp/function/function.kt
  app/src/main/res/drawable/img_abathur.webp
  app/src/main/res/drawable/img_artanis.webp
  app/src/main/res/drawable/img_jim.webp
  app/src/main/res/drawable/img_kerrigan.webp
  app/src/main/res/drawable/img_mengsk.webp
  app/src/main/res/drawable/img_overmind.webp
  app/src/main/res/drawable/img_stukov.webp
  app/src/main/res/drawable/img_tychus.webp
  app/src/main/res/drawable/img_vorazun.webp
  app/src/main/res/drawable/img_zeratul.webp
Labels: add, fix, docs

#9 다이얼로그 화면에 띄우기
  app/src/main/java/com/example/contactapp/presentation/AddContact.kt
  app/src/main/java/com/example/contactapp/presentation/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/custom_dialog.xml
Labels: add

#11 [FEAT] 뷰페이저, 탭레이아웃 생성
  .idea/gradle.xml
  app/build.gradle.kts
  app/src/main/java/com/example/contactapp/function/FragmentViewPagerAdapter.kt
  app/src/main/java/com/example/contactapp/presentation/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: bug

#13 mypage to dev
  .idea/misc.xml
  app/src/main/java/com/example/contactapp/data/DataSource.kt
  app/src/main/java/com/example/contactapp/function/function.kt
  app/src/main/java/com/example/contactapp/presentation/MyPageFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: add, fix

#14 [feat] ContactListFragment
  app/src/main/java/com/example/contactapp/function/FragmentDataListener.kt
  app/src/main/java/com/example/contactapp/function/function.kt
  app/src/main/java/com/example/contactapp/presentation/ContactListAdapter.kt
  app/src/main/java/com/example/contactapp/presentation/ContactListFragment.kt
  app/src/main/res/drawable/background_circle.xml
  app/src/main/res/drawable/background_search.xml
  app/src/main/res/drawable/ic_heart.png
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/list_item_layout.xml
  app/src/main/res/values/colors.xml
  gradle/libs.versions.toml
Labels: add

#16 레이아웃 아이디 변경
  app/src/main/java/com/example/contactapp/presentation/AddContact.kt
  app/src/main/res/layout/custom_dialog.xml
Labels: add

#19 + 눌렀을때 add 다이얼로그 띄우기 기능 추가
  app/src/main/java/com/example/contactapp/data/data.kt
  app/src/main/java/com/example/contactapp/presentation/MyPageFragment.kt
Labels: add

#17 [FIX] Contact List 맨 밑 스크롤 안되는 버그 해결
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_contact_list.xml
Labels: bug

#18 [feat] itemClick
  app/src/main/java/com/example/contactapp/function/FragmentDataListener.kt
  app/src/main/java/com/example/contactapp/presentation/ContactListFragment.kt
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/list_item_layout.xml
  gradle/libs.versions.toml
Labels: help wanted, fix

#22 [FEAT][FIX] Glide API를 통해 화면 전환 속도 기능 개선
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contactapp/data/data.kt
  app/src/main/java/com/example/contactapp/function/function.kt
  app/src/main/java/com/example/contactapp/presentation/ContactListAdapter.kt
Labels: bug, add

#25 검색창 안생기는 버그 수정
  app/src/main/java/com/example/contactapp/presentation/ContactListFragment.kt
  app/src/main/res/layout/fragment_contact_list.xml
Labels: fix

#29 [feat] fab ClickListener
  app/build.gradle.kts
  app/src/main/java/com/example/contactapp/function/FragmentViewPagerAdapter.kt
  app/src/main/java/com/example/contactapp/presentation/ContactListFragment.kt
  app/src/main/java/com/example/contactapp/presentation/MainActivity.kt
  app/src/main/java/com/example/contactapp/presentation/MyPageFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: fix

#36 [FEAT] 선택구현1 레이아웃 변경
  app/src/main/java/com/example/contactapp/presentation/ContactListFragment.kt
  app/src/main/java/com/example/contactapp/presentation/GridSpaceItemDecoration.kt
  app/src/main/res/layout/fragment_contact_list.xml
Labels: add

#40 디테일에서 스와이프되는 문제 해결
  app/src/main/java/com/example/contactapp/presentation/ContactDetailFragment.kt
  app/src/main/java/com/example/contactapp/presentation/ContactListFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_contact_list.xml
Labels: fix

#42 미완 - 전화 기록 가져오기
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contactapp/function/FragmentViewPagerAdapter.kt
  app/src/main/java/com/example/contactapp/presentation/ContactDetailFragment.kt
  app/src/main/java/com/example/contactapp/presentation/ContactListFragment.kt
  app/src/main/java/com/example/contactapp/presentation/MainActivity.kt
  app/src/main/java/com/example/contactapp/presentation/call_log/CallLogAdapter.kt
  app/src/main/res/layout/call_log_item.xml
  app/src/main/res/layout/fragment_contact_detail.xml
Labels: add

#43 불필요한 코드 몇개 제거
  app/src/main/java/com/example/contactapp/presentation/AddContact.kt
  app/src/main/java/com/example/contactapp/presentation/ContactDetailFragment.kt
  app/src/main/java/com/example/contactapp/presentation/MainActivity.kt
  app/src/main/java/com/example/contactapp/presentation/MyPageFragment.kt
Labels: fix

#45 dev to main
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contactapp/data/CallInformation.kt
  app/src/main/java/com/example/contactapp/data/ContactInformation.kt
  app/src/main/java/com/example/contactapp/data/DataSource.kt
  app/src/main/java/com/example/contactapp/data/data.kt
  app/src/main/java/com/example/contactapp/function/FragmentViewPagerAdapter.kt
  app/src/main/java/com/example/contactapp/function/function.kt
  app/src/main/java/com/example/contactapp/presentation/AddContact.kt
  app/src/main/java/com/example/contactapp/presentation/ContactDetailFragment.kt
  app/src/main/java/com/example/contactapp/presentation/ContactListAdapter.kt
  app/src/main/java/com/example/contactapp/presentation/ContactListFragment.kt
  app/src/main/java/com/example/contactapp/presentation/GridSpaceItemDecoration.kt
  app/src/main/java/com/example/contactapp/presentation/MainActivity.kt
  app/src/main/java/com/example/contactapp/presentation/MyPageFragment.kt
  app/src/main/java/com/example/contactapp/presentation/call_log/CallLogAdapter.kt
  app/src/main/res/drawable/background_circle.xml
  app/src/main/res/drawable/background_search.xml
  app/src/main/res/drawable/ic_create.xml
  app/src/main/res/drawable/ic_delete.png
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_heart.png
  app/src/main/res/drawable/ic_rewrite.png
  app/src/main/res/drawable/img_abathur.webp
  app/src/main/res/drawable/img_artanis.webp
  app/src/main/res/drawable/img_jim.webp
  app/src/main/res/drawable/img_kerrigan.webp
  app/src/main/res/drawable/img_mengsk.webp
  app/src/main/res/drawable/img_overmind.webp
  app/src/main/res/drawable/img_stukov.webp
  app/src/main/res/drawable/img_tychus.webp
  app/src/main/res/drawable/img_vorazun.webp
  app/src/main/res/drawable/img_zeratul.webp
  app/src/main/res/drawable/svg_call.xml
  app/src/main/res/drawable/svg_message.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/call_log_item.xml
  app/src/main/res/layout/custom_dialog.xml
  app/src/main/res/layout/fragment_contact_detail.xml
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/list_item_layout.xml
  app/src/main/res/menu/popup_menu.xml
  app/src/main/res/menu/toolbar_menu.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: add

#46 ContactDetailFragment - 권한 요청 변경
  app/src/main/java/com/example/contactapp/presentation/ContactDetailFragment.kt
Labels: fix
